I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
INFO:root:Get NLC data in /gss_gpfs_scratch/dong.r/Dataset/BCI/Sublex/1/1/train/sub
INFO:root:Vocabulary size: 30
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: Tesla K40m
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:0b:00.0
Total memory: 11.17GiB
Free memory: 11.09GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40m, pci bus id: 0000:0b:00.0)
INFO:root:Creating 3 layers of 512 units.
Traceback (most recent call last):
  File "train.py", line 213, in <module>
    tf.app.run()
  File "/home/dong.r/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "train.py", line 210, in main
    train()
  File "train.py", line 95, in train
    model, epoch = create_model(sess, vocab_size, False)
  File "train.py", line 46, in create_model
    flag_bidirect=FLAGS.flag_bidirect, model_sum=FLAGS.flag_sum)
  File "/home/dong.r/BCI/model_concat.py", line 296, in build_model
    self.setup_train()
  File "/home/dong.r/BCI/model_concat.py", line 83, in setup_train
    gradients = tf.gradients(self.losses, params)
AttributeError: 'Model' object has no attribute 'losses'
